# Generated by Django 5.1.1 on 2024-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_description_alter_role_color_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='message',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='responder',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_responder',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
