# Generated by Django 5.1.1 on 2024-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_reply_message_remove_reply_responder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
