# Generated by Django 5.1.1 on 2024-09-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_reviewed',
        ),
    ]
