# Generated by Django 5.1.1 on 2024-09-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='fbk_content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='fbk_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='sender',
            new_name='fbk_sender',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='sent_at',
            new_name='fbk_sent_at',
        ),
    ]
